### ISSUE TITLE
Uploader.Upload - MediaFireApiError: 128: Required parameters missing

### ISSUE THREAD

**Issue by adam-schons** [MediaFire/mediafire-python-open-sdk#29]
I'm trying to figure out the issue with my code.
I have tried to base my code off of the examples in the uploader(session) and mediafire.MediaFireUploader on the GitHub page.

Code, running python 2.7.11rc1 :
`import os, Tkinter, tkFileDialog, logging, pprint
logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
from mediafire import (MediaFireApi, MediaFireUploader)

#Log in
api = MediaFireApi()
session = api.user_get_session_token(app_id='42511',
                                     email='email',
                                     password='password')

api.session = session
uploader = MediaFireUploader(api)

#Get the location of folder with documents to upload
root = Tkinter.Tk()
uploadDirectory = tkFileDialog.askdirectory(parent=root, initialdir="/", title='Please select a directory')
dirs = os.listdir(uploadDirectory)

#Get FolderKey from user for folder to upload into
folderKey = raw_input("What is the folder key? ")
folderKey = "mf:" + folderKey

#Set iteration to see how many files have been evaluated
i=0

#Loop specified directory files for upload
for File in dirs:
    flPath = uploadDirectory + "/" + File #Set File Full Path
    fd = open(flPath,'rb') #Set file location as object
    result = uploader.upload(fd, name=File, folder_key=folderKey, action_on_duplicate="skip")
    pprint(api.file_get_info(result.quickkey))
    print(i)
    i+=1        `

Console Results:
DEBUG:mediafire.uploader:Calculating checksum
DEBUG:mediafire.api:uri=/api/1.3/upload/check.php query=filename=file.pdf&folder_key=mf%3A97ol3i4z62bzu&hash=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855&response_format=json&resumable=no&session_token=13dfda90c6a4d0f59776be4db81120f467c13912bb831a31e7223916178bb846f352d22289f974beaa912ded2d1bada04f4202facdf2c745e3f68222cdfd0bd9d898690c346e7938&size=0&signature=01d87ccaa5494f2cf39bce303d5095c2
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: www.mediafire.com
DEBUG:requests.packages.urllib3.connectionpool:"POST /api/1.3/upload/check.php HTTP/1.1" 400 None
DEBUG:mediafire.api:response: {"response":{"action":"upload\/check","message":"Required parameters for this request are missing","error":128,"result":"Error","new_key":"yes","current_api_version":"1.5"}}
Traceback (most recent call last):
  File "C:\Users\Adam\My Documents\LiClipse Workspace\MediaFireLinks\MediaFireUpload.py", line 32, in <module>
    result = uploader.upload(fd, name=File, folder_key=folderKey, action_on_duplicate="skip")
  File "C:\Python27\lib\site-packages\mediafire\uploader.py", line 262, in upload
    check_result = self._upload_check(upload_info, resumable)
  File "C:\Python27\lib\site-packages\mediafire\uploader.py", line 387, in _upload_check
    resumable=resumable
  File "C:\Python27\lib\site-packages\mediafire\api.py", line 568, in upload_check
    'resumable': resumable
  File "C:\Python27\lib\site-packages\mediafire\api.py", line 197, in request
    return self._process_response(response)
  File "C:\Python27\lib\site-packages\mediafire\api.py", line 236, in _process_response
    response_node['error'])
mediafire.api.MediaFireApiError: 128: Required parameters for this request are missing

**Comment by roman-yepishev** [comment]
Right away I see you are using mf: prefix when setting the folder, you want to use that prefix only when interacting with the mediafire.client module. Try using client.upload_file or not supplying the mf: prefix to upload() method.

**Comment by adam-schons** [comment]
Thank you Roman for noticing that.  

I have run the script again and came up with the same result for the MediaFireApiError: 128.  The second DEBUG entry does list the correct folder_key this time however.

I had initially used the client.upload_file and decided to attempt the more specific uploader.upload so I could specify the skip duplicate attribute.  
Per the solved issue #18 it looks like the client.upload-file() can accept directories, would I place the directory path in lieu of the file path.
If I were to use the client.upload_file(Path, mf:folder_key), it looks like the action_on_duplicate would be set to 'replace' in client.py.  Am I following that correctly?  If I were to change 'replace' to 'skip' in client.py then I should be able to use client.upload_file to achieve my goal?

Thank you for your time,
Adam

**Comment by roman-yepishev** [comment]
The client will not upload directory contents, #18 is not yet resolved.

I was also able to upload the directory using your script w/o an API error, but I see that your script sent a file size of 0. 0-sized files are a special case in MediaFire API (and that is not handled in the python library) and need to be created via file/create API call.

**Comment by adam-schons** [comment]
Success!!!
One of my files had a size of 0 which was causing the issue.

Thank you very much Roman!
